--- !<io.dekorate.docker.config.EditableDockerBuildConfig>
project:
  root: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/Chapter%2010/
  dekorateInputDir: null
  dekorateOutputDir: META-INF/dekorate
  dekorateMetaDir: ../.dekorate
  buildInfo:
    name: scanner
    version: 0.0.1-SNAPSHOT
    packaging: jar
    buildTool: maven
    buildToolVersion: 3.6.3
    outputFile: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/Chapter%2010/target/scanner-0.0.1-SNAPSHOT.jar
    classOutputDir: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/Chapter%2010/target/classes/
    resourceDir: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/Chapter%2010/src/main/resources/
  scmInfo:
    root: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/
    branch: main
    commit: a4c3d3ca476ba0238d70bd8197fa4a7924089355
    remote:
      '[remote "origin"]': https://github.com/PacktPublishing/Effortless-Cloud-Native-Apps-Development-using-Skaffold.git
partOf: ""
name: scanner
version: 0.0.1-SNAPSHOT
registry: null
group: ashish
image: null
dockerFile: null
autoBuildEnabled: false
autoPushEnabled: false
enabled: null
autoDeployEnabled: null
