---
project:
  root: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/Chapter%2010/
  dekorateInputDir: null
  dekorateOutputDir: META-INF/dekorate
  dekorateMetaDir: ../.dekorate
  buildInfo:
    name: scanner
    version: 0.0.1-SNAPSHOT
    packaging: jar
    buildTool: maven
    buildToolVersion: 3.6.3
    outputFile: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/Chapter%2010/target/scanner-0.0.1-SNAPSHOT.jar
    classOutputDir: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/Chapter%2010/target/classes/
    resourceDir: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/Chapter%2010/src/main/resources/
  scmInfo:
    root: file:///Users/ashish/Downloads/github/Effortless-Cloud-Native-Apps-Development-using-Skaffold/
    branch: main
    commit: a4c3d3ca476ba0238d70bd8197fa4a7924089355
    remote:
      '[remote "origin"]': https://github.com/PacktPublishing/Effortless-Cloud-Native-Apps-Development-using-Skaffold.git
partOf: ""
name: scanner
version: 0.0.1-SNAPSHOT
workingDir: ""
serviceAccount: ""
host: ""
ports:
  - name: http
    containerPort: 8080
    hostPort: 80
    path: /
    protocol: null
serviceType: LoadBalancer
imagePullPolicy: IfNotPresent
livenessProbe:
  httpActionPath: /actuator/info
  execAction: ""
  tcpSocketAction: ""
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  httpActionPath: /actuator/health
  execAction: ""
  tcpSocketAction: ""
  initialDelaySeconds: 0
  periodSeconds: 30
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 3
requestResources:
  memory: ""
  cpu: ""
limitResources:
  memory: ""
  cpu: ""
expose: false
autoDeployEnabled: false
replicas: 1
deploymentStrategy: None
rollingUpdate:
  maxUnavailable: 25%
  maxSurge: 25%
headless: false
