# Default values for reactive-web-app-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imageKey:
  repository: gcr.io/basic-curve-316617
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080